name: access
version: 1.3.0
description: A simple database utility for the entity library and PostgreSQL.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/access
documentation: https://github.com/rikulo/access
dev_dependencies:
  test: any
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  entity: ">=0.7.0"
  postgresql2: '>=0.5.0'
  logging: ">=0.11.0 <2.0.0"
  rikulo_commons: '>=3.0.0'
