name: access
version: 3.9.0
description: A simple database utility for the entity library and PostgreSQL.
homepage: https://github.com/rikulo/access
documentation: https://github.com/rikulo/access
dev_dependencies:
  test: any
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  entity: any
  postgresql2: any
  logging: any
  rikulo_commons: any
  charcode: any
