name: access
version: 0.5.4
description: > 
  A simple database utility for the entity library and PostgreSQL.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/access
documentation: https://github.com/rikulo/access
dev_dependencies:
  unittest: any
environment:
  sdk: ">=1.4.0"
dependencies:
  entity: ">=0.7.0"
  postgresql2: any
  logging: any
