name: access
version: 3.6.1
description: A simple database utility for the entity library and PostgreSQL.
homepage: https://github.com/rikulo/access
documentation: https://github.com/rikulo/access
dev_dependencies:
  test: any
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  entity: ">=2.5.0"
  postgresql2: '>=0.5.0'
  logging: ">=0.11.0 <2.0.0"
  rikulo_commons: '>=3.0.0'
  charcode: any
